import type { ParcelCaseTemplate } from '../simulation/types';

export const CASE_TEMPLATES: ParcelCaseTemplate[] = [
  {
    id: 'tea-safe', parcelName: 'Moonpetal Tea', minShift: 0, verdict: 'accept', issue: 'clear',
    explanation: 'The seal, label, and contents are all clear.',
    visibleHints: ['Seal intact', 'Postage paid'], decisiveTool: 'xray',
    clues: { xray: 'Dried leaves and a ceramic infuser.', resonance: 'A soft leafy rustle.', aura: 'Calm silver aura.' },
    incident: 'The parcel glides into the outgoing chute.',
    style: { bodyColor: 0x475d78, ribbonColor: 0xd8c46a, shape: 'box', emblem: 'moon' },
  },
  {
    id: 'boots-safe', parcelName: 'Seven-League Boot Polish', minShift: 0, verdict: 'accept', issue: 'clear',
    explanation: 'Oddly fast boot polish is still legal.',
    visibleHints: ['Licensed maker', 'Seal intact'], decisiveTool: 'aura',
    clues: { xray: 'Two tins and a tiny brush.', resonance: 'No movement detected.', aura: 'Stable cobalt aura.' },
    incident: 'A postage sprite carries it away at impressive speed.',
    style: { bodyColor: 0x6b4a3a, ribbonColor: 0x4cb5c4, shape: 'satchel', emblem: 'star' },
  },
  {
    id: 'cookies-safe', parcelName: 'Graveyard Biscuits', minShift: 0, verdict: 'accept', issue: 'clear',
    explanation: 'The skull shape is branding, not contraband.',
    visibleHints: ['Food permit attached', 'No damage'], decisiveTool: 'resonance',
    clues: { xray: 'Twelve bone-shaped biscuits.', resonance: 'A harmless biscuit rattle.', aura: 'Faint cinnamon aura.' },
    incident: 'The parcel leaves behind one delicious crumb.',
    style: { bodyColor: 0x5d3d50, ribbonColor: 0xe4b56d, shape: 'box', emblem: 'bone' },
  },
  {
    id: 'damaged-vial', parcelName: 'Raincloud Tonic', minShift: 0, verdict: 'return', issue: 'damaged',
    explanation: 'The package is visibly damaged and must be returned.',
    visibleHints: ['Corner crushed', 'Moisture warning'],
    clues: { xray: 'One cracked glass vial.', resonance: 'Drip… drip… drip.', aura: 'Unstable damp aura.' },
    incident: 'A tiny raincloud sneezes before the return chute closes.',
    style: { bodyColor: 0x3f6685, ribbonColor: 0x9fcff0, shape: 'box', emblem: 'moon', damaged: true },
  },
  {
    id: 'broken-seal', parcelName: 'Royal Eye Cream', minShift: 0, verdict: 'return', issue: 'broken seal',
    explanation: 'The security seal has already been opened.',
    visibleHints: ['Wax seal split', 'Sender verified'],
    clues: { xray: 'A jar with something blinking inside.', resonance: 'Polite blinking noises.', aura: 'Cosmetic-grade enchantment.' },
    incident: 'The jar winks as the parcel is sent back.',
    style: { bodyColor: 0x745173, ribbonColor: 0xe4c56c, shape: 'box', emblem: 'eye', damaged: true },
  },
  {
    id: 'live-egg', parcelName: 'Decorative Dragon Egg', minShift: 0, verdict: 'quarantine', issue: 'living cargo',
    explanation: 'A heartbeat means undeclared living cargo.',
    visibleHints: ['Marked “ornamental”', 'Warm to touch'], decisiveTool: 'resonance',
    clues: { xray: 'An intact egg with a curled shape inside.', resonance: 'Fast double heartbeat detected!', aura: 'Young ember aura.' },
    incident: 'The egg cracks and a tiny nose breathes a smoke ring.',
    style: { bodyColor: 0x71463d, ribbonColor: 0xf0a34a, shape: 'box', emblem: 'flame' },
  },
  {
    id: 'mimic', parcelName: 'Ordinary Storage Box', minShift: 0, verdict: 'quarantine', issue: 'living cargo',
    explanation: 'The parcel itself is alive. Mimics require quarantine.',
    visibleHints: ['No return address', 'Unusual tooth marks'], decisiveTool: 'resonance',
    clues: { xray: 'Rows of teeth where packing foam should be.', resonance: 'Slow breathing detected!', aura: 'Hungry amber aura.' },
    incident: 'The box snaps at the stamp and is caged by the chute.',
    style: { bodyColor: 0x6e4e3a, ribbonColor: 0xcaa36a, shape: 'box', emblem: 'eye' },
  },
  {
    id: 'underpaid', parcelName: 'Bottomless Sock', minShift: 1, verdict: 'return', issue: 'unpaid postage',
    explanation: 'Dimensional postage is missing from the label.',
    visibleHints: ['Postage: 2g', 'Required: 12g'],
    clues: { xray: 'The scan continues beyond the machine.', resonance: 'A distant ocean can be heard.', aura: 'Legal dimensional weave.' },
    incident: 'A wave splashes out before the sock is returned.',
    style: { bodyColor: 0x344b68, ribbonColor: 0xe7868d, shape: 'satchel', emblem: 'star' },
  },
  {
    id: 'cursed-doll', parcelName: 'Definitely Normal Doll', minShift: 1, verdict: 'quarantine', issue: 'cursed aura',
    explanation: 'The violet aura marks a binding curse.',
    visibleHints: ['Gift wrapped', 'No maker listed'], decisiveTool: 'aura',
    clues: { xray: 'A small wooden doll facing the scanner.', resonance: 'It whispers your employee number.', aura: 'Severe violet curse detected!' },
    incident: 'The doll waves goodbye from inside a containment jar.',
    style: { bodyColor: 0x583a63, ribbonColor: 0xd76997, shape: 'box', emblem: 'eye' },
  },
  {
    id: 'lucky-moss', parcelName: 'Lucky Pocket Moss', minShift: 1, verdict: 'accept', issue: 'clear',
    explanation: 'The glow is a harmless luck charm.',
    visibleHints: ['Botanical permit', 'Postage paid'], decisiveTool: 'aura',
    clues: { xray: 'A padded jar of moss.', resonance: 'Quiet photosynthesis.', aura: 'Benign green luck aura.' },
    incident: 'A gold coin tumbles from the accepted parcel.',
    style: { bodyColor: 0x446143, ribbonColor: 0xb7ce67, shape: 'tube', emblem: 'leaf' },
  },
  {
    id: 'forged-label', parcelName: 'Museum Moonstone', minShift: 2, verdict: 'return', issue: 'forged label',
    explanation: 'The label says moonstone, but the X-ray shows common brick.',
    visibleHints: ['High-value declaration', 'Suspiciously light'], decisiveTool: 'xray',
    clues: { xray: 'One red brick and three pebbles.', resonance: 'A very ordinary clunk.', aura: 'No lunar resonance.' },
    incident: 'The “moonstone” sheds a very earthly puff of dust.',
    style: { bodyColor: 0x354a72, ribbonColor: 0xd9d6d0, shape: 'box', emblem: 'moon' },
  },
  {
    id: 'phoenix-feather', parcelName: 'Phoenix Feather Pillow', minShift: 2, verdict: 'quarantine', issue: 'volatile core',
    explanation: 'The parcel contains an undeclared ignition source.',
    visibleHints: ['Bedding permit', 'Surface unusually hot'], decisiveTool: 'xray',
    clues: { xray: 'A live ember core inside the pillow!', resonance: 'Crackling grows louder.', aura: 'Combustion threshold exceeded.' },
    incident: 'The quarantine bell rings as harmless sparks spell “oops”.',
    style: { bodyColor: 0x8b413d, ribbonColor: 0xffb14e, shape: 'box', emblem: 'flame' },
  },
  {
    id: 'cold-candle', parcelName: 'Everfrost Candle', minShift: 2, verdict: 'accept', issue: 'clear',
    explanation: 'Cold flame is unusual but properly licensed.',
    visibleHints: ['Elemental permit', 'Insulated tube'], decisiveTool: 'xray',
    clues: { xray: 'A secured blue candle.', resonance: 'Gentle icy crackle.', aura: 'Stable frost enchantment.' },
    incident: 'A snowflake lands on the acceptance stamp.',
    style: { bodyColor: 0x3d6382, ribbonColor: 0xb6ecff, shape: 'tube', emblem: 'flame' },
  },
  {
    id: 'timepiece', parcelName: 'Grandfather’s Pocket Watch', minShift: 3, verdict: 'quarantine', issue: 'time echo',
    explanation: 'The watch ticks tomorrow’s time. Temporal cargo is quarantined.',
    visibleHints: ['Antique declaration', 'Date mailed: tomorrow'], decisiveTool: 'resonance',
    clues: { xray: 'Gears turning in both directions.', resonance: 'Two overlapping tick patterns!', aura: 'Chronal echo detected.' },
    incident: 'For one second, the result stamp appears before you press it.',
    style: { bodyColor: 0x5b4c39, ribbonColor: 0xd4ae58, shape: 'box', emblem: 'star' },
  },
  {
    id: 'future-cake', parcelName: 'Tomorrow Cake', minShift: 3, verdict: 'return', issue: 'forged label',
    explanation: 'The delivery date predates the baking date. The label is invalid.',
    visibleHints: ['Baked: Thursday', 'Delivered: Wednesday'],
    clues: { xray: 'A perfectly ordinary cake.', resonance: 'Faint celebratory music.', aura: 'Minor, legal freshness charm.' },
    incident: 'The icing rewrites itself to say “try again yesterday”.',
    style: { bodyColor: 0x784d65, ribbonColor: 0xf6c0cc, shape: 'box', emblem: 'star' },
  },
  {
    id: 'singing-stone', parcelName: 'Choir Stone', minShift: 3, verdict: 'accept', issue: 'clear',
    explanation: 'No rule prohibits rocks with excellent pitch.',
    visibleHints: ['Performance permit', 'Seal intact'], decisiveTool: 'resonance',
    clues: { xray: 'A smooth stone on velvet.', resonance: 'Perfect three-part harmony.', aura: 'Harmless artistic aura.' },
    incident: 'The outgoing chute answers with a bass note.',
    style: { bodyColor: 0x555a6f, ribbonColor: 0xc78fd8, shape: 'satchel', emblem: 'star' },
  },
  {
    id: 'shadow-bottle', parcelName: 'Bottled Shade', minShift: 4, verdict: 'quarantine', issue: 'cursed aura',
    explanation: 'The bottle contains a predatory shadow curse.',
    visibleHints: ['Light-sensitive', 'Shadow points the wrong way'], decisiveTool: 'aura',
    clues: { xray: 'An empty bottle casting a full silhouette.', resonance: 'Scratching from behind you.', aura: 'Predatory black-violet curse!' },
    incident: 'The shadow tries to flee, then folds into the quarantine stamp.',
    style: { bodyColor: 0x25233f, ribbonColor: 0x8e70c1, shape: 'tube', emblem: 'eye' },
  },
  {
    id: 'star-seeds', parcelName: 'Pocket Star Seeds', minShift: 4, verdict: 'accept', issue: 'clear',
    explanation: 'Miniature stars are permitted below the brightness limit.',
    visibleHints: ['Brightness: Class I', 'Astral permit'], decisiveTool: 'aura',
    clues: { xray: 'Six tiny points of light.', resonance: 'A distant celestial hum.', aura: 'Brightness safely below limit.' },
    incident: 'The accepted parcel leaves a sparkling trail.',
    style: { bodyColor: 0x303867, ribbonColor: 0xf3d46c, shape: 'box', emblem: 'star' },
  },
  {
    id: 'fizz-root', parcelName: 'Carbonated Mandrake', minShift: 4, verdict: 'quarantine', issue: 'living cargo',
    explanation: 'The root is alive, loud, and entirely undeclared.',
    visibleHints: ['Marked as soda', 'Box occasionally hiccups'], decisiveTool: 'resonance',
    clues: { xray: 'A root creature holding its breath.', resonance: 'Heartbeat plus fizzy hiccups!', aura: 'Living botanical aura.' },
    incident: 'The mandrake burps bubbles all the way to quarantine.',
    style: { bodyColor: 0x486044, ribbonColor: 0xe3ca65, shape: 'box', emblem: 'leaf' },
  },
  {
    id: 'lava-lamp', parcelName: 'Actual Lava Lamp', minShift: 4, verdict: 'quarantine', issue: 'volatile core',
    explanation: 'The lamp contains actual pressurized lava.',
    visibleHints: ['Home décor declaration', 'Heat shield missing'], decisiveTool: 'xray',
    clues: { xray: 'Pressurized molten rock!', resonance: 'Deep volcanic bubbling.', aura: 'Critical thermal instability.' },
    incident: 'A containment bubble catches one dramatic lava blob.',
    style: { bodyColor: 0x6d3731, ribbonColor: 0xf28a42, shape: 'tube', emblem: 'flame' },
  },
];
